- bcftbx/IlluminaData.py
- bcftbx/test/test_IlluminaData.py
The outputs of `bcl2fastq` v2 vary depending on the contents of the `Sample_ID` and `Sample_Name` fields in the sample sheet:
- if `Sample_ID` and `Sample_Name` are the same then `Sample_Name` is used as the sample name in the output fastq file and the fastq is written to the "top-level" of the project directory;
- if `Sample_ID` and `Sample_Name` differ then `Sample_Name` is used as the sample name in the output fastq file but the fastq is written to the a subdirectory called `Sample_ID` under the "top-level" of the project directory;
- if `Sample_Name` is empty then `Sample_ID`  is used as the sample name in the output fastq file and the fastq is written to the "top-level" of the project directory;
Currently only the first case is handled by the code in `bcftbx/IlluminaData.py` (and …
> bcftbx/IlluminaData: handle "special cases" for bcl2fastq v2 outputs

- bcftbx/IlluminaData.py
- bcftbx/test/test_IlluminaData.py
PR to address failures when the `IlluminaFastq` and `IlluminaData` classes try to handle "non-canonical" Fastq names e.g.
PB04_S4_R1_unpaired.fastq.gz
PB04_trimmoPE_bowtie2_notHg38.1.fastq.gz
> Fix IlluminaData classes to handle non canonical Fastq names

- ChIP-seq/make_macs2_xls.py
- bcftbx/Spreadsheet.py
- bcftbx/simple_xls.py
- bcftbx/test/test_simple_xls.py
- setup.py
This PR adds a new function `save_as_xlsx` to the `XLSWorkBook` class of `bcftbx/simple_xls.py`, which enables the workbook to be saved in XLSX format.
This functionality co-exists with the `save_as_xls` function, so XLS output continues to be available.
> Enable functionality to output XLSX files from simple_xls.py

- bcftbx/JobRunner.py
- bcftbx/Pipeline.py
- bcftbx/test/test_JobRunner.py
- bcftbx/test/test_Pipeline.py
PR to implement the suggestions in issue #27, to capture the exit status of commands run by the various `JobRunner` classes and the `Pipeline.Job` class so that it's available to the calling subprogram.
> Capture the exit status of jobs from JobRunner and Pipeline.Job classes

- bcftbx/IlluminaData.py
- bcftbx/test/test_IlluminaData.py
- illumina2cluster/prep_sample_sheet.py
PR to update how the prediction of sample sheet outputs is handled in `bcftbx/IlluminaData.py`, by implementing a new `SampleSheetPredictor` class.
The code is based on the predictor class originally found in `auto_process_ngs` PR 30:
https://github.com/fls-bioinformatics-core/auto_process_ngs/pull/30
> Update samplesheet prediction and checking

- bcftbx/IlluminaData.py
- bcftbx/test/test_IlluminaData.py
Prediction of sample index by the `SampleSheetPredictor` class is incorrect when the supplied sample sheet has lanes not in ascending numerical order (e.g. lane 2 appears before lane 1).
In these cases Illumina's `bcl2fastq` software appears to order the lanes before assigning sample index numbers, so the indices are not equivalent to the line number of the sample in the `[Data]` section of the SampleSheet.
This PR aims to address this issue by updating the predictor to correctly handle this novel case.
> Fix output prediction when Sample Sheet has lanes out of order

- QC-pipeline/fastq_screen.sh
- share/bcftbx.versions.sh
This PR updates the `fastq_screen.sh` script in the `QC-pipeline` directory to handle the latest version of Babraham's Fastq Screen program.
The updates include:
* Ensure that only versions between 0.6.0 and 0.6.2 trigger premature exit for `--subset 0`
* Exit if `--color` option is specified for versions 0.6.0 and later (as it's no longer supported)
* Handle new format for version string output by `fastq_screen --version` for 0.9.2
* Ensure script recognises 0.9.* versions
> Update QC to handle Fastq_screen v0.9.2

- bcftbx/IlluminaData.py
- bcftbx/test/test_IlluminaData.py
PR which fixes the broken handling of duplicates for IEM samplesheets which don't have an `index` column in the `[Data]` section.
The `bcl2fastq` 2.17 documentation is ambiguous about whether the `index` column is obligatory, but in practice it seems that it can be omitted for situations where there is only one sample (when essentially it's the same as having an empty `index`).
> Fix handling duplicates in IEM samplesheets which have no 'index' column

- bcftbx/FASTQFile.py
- bcftbx/test/test_FASTQFile.py
PR that enables the use of the equality operator for `FastqRead` objects, so that two reads can be compared.
> Add support for equality operator (==) to FastqRead class

- bcftbx/IlluminaData.py
- bcftbx/test/test_IlluminaData.py
PR which enables the `IlluminaFastq` class in `bcftbx/IlluminaData.py` to handle index read Fastq file names. These have the same format as canonical Illumina Fastq names but use `I1/2` instead of `R1/2`, e.g.
NA10831_S7_L002_I1_001.fastq.gz
> Update IlluminaFastq class to handle index read fastq file names

- bcftbx/JobRunner.py
WIP PR which explicitly sets the exit status for terminated jobs in the `GEJobRunner` class, with the intention of avoiding pointless multiple calls to `qacct` when trying to fetch the exit status later on.
> WIP Explicitly set exit status for terminated jobs in GEJobRunner

- bcftbx/FASTQFile.py
- bcftbx/test/test_FASTQFile.py
PR to fix the `FastqIterator` and `FastqRead` classes in `bcftbx/FASTQFile.py` to deal with Fastq files that contain reads with "empty" (i.e. zero-length) sequences e.g.:
1 |@73D9FA:3:FC:1:1:7488:1000 1:N:0:
2 |
3 |+
4 |
Leaving aside the issue of whether or not these are valid Fastq read records, in practice they can be produced e.g. by `cutadapt` if (say) a read starts with adapter sequence that is being trimmed off.
In most cases `FastqIterator` could already handle these reads, however there is an edge case (related to the buffered approach of reading in the data from file) which meant that it was possible for a line to be 'dropped', resulting in incorrect read data. This PR adds a test for this edge case and fixes the issue.
> Fix FastqIterator and FastqRead classes to handle "empty" sequences

- bcftbx/IlluminaData.py
- bcftbx/mock.py
- bcftbx/test/test_IlluminaData.py
PR attempts to fix an edge case for the `IlluminaData` class when there is `bcl2fastqv2`-style output with Fastq files that are in subdirectories which are called the same name as the sample.
For example: for a Fastq file in project `AB` and sample `AB1`:
bcl2fastq/AB/AB1/AB1_S1_L001_R1_001.fastq.gz
According to my understanding of the `bcl2fastq` v2 manual, it shouldn't be possible to generate this arrangement as the "sample"-level subdirectories (`AB1` in the example above) should only be created when the name differs from the ID as supplied in the sample sheet.
However as this case has been encountered in output from 10xGenomics `cellranger mkfastq` command, this PR updates the relevant code to be able to handle the situation.
> Fix IlluminaData for bcl2fastq2 output where Fastqs are in subdirs with same name as sample

- QC-pipeline/fastq_screen.sh
- QC-pipeline/illumina_qc.sh
- bcftbx/Pipeline.py
- bcftbx/qc/report.py
- bcftbx/qc/test/test_report.py
- bcftbx/test/test_Pipeline.py
PR to update the QC pipeline and scripts to handle `.fq[.gz]` Fastq files:
* Update `GetFastqFiles` and `GetFastqGzFiles` functions in `bcftbx/Pipeline.py` to pick up Fastq files with `.fq[.gz]` extensions
* Update `strip_ngs_extensions` function in `bcftbx/qc/report.py` to also remove `.fq` extensions
* Update the `illumina_qc.sh` and `fastq_screen.sh` scripts in `QC-pipeline` to handle outputs for files with `.fq` extension
> Update QC pipeline infrastructure and scripts to handle .fq(.gz) files

- NGS-general/uncompress_fastqgz.sh
- QC-pipeline/fastq_screen.sh
- QC-pipeline/illumina_qc.sh
- QC-pipeline/solid_qc.sh
- share/bcftbx.functions.sh
- share/bcftbx.ngs_utils.sh
PR to address issue #42 where the `illumina_qc.sh` script would sometimes fail to complete, leaving behind the temporary directories used to run the QC in.
The problem appears to be a combination of factors:
* The `set_permissions_and_group` function (used to to invoke `chmod` and `chgrp` from `illumina_qc.sh`) was being run on all files and directories in the current directory (i.e. not just the `qc` dir)
* When `illumina_qc.sh` was run multiple times simultaneously in the same directory (typical when QC'ing a set of Fastqs from a sequencing run), these operations invoked in one run might then try to change the attributes on the temporary files from another while those files were being removed. In this case the operations would fail and terminate the script.
The PR makes changes to …
> Fix failing chmod/chgrp operations in illumina_qc.sh script

- QC-pipeline/fastq_screen.sh
- QC-pipeline/illumina_qc.sh
PR to implement a `--qc_dir` option on the `QC-pipeline/illumina_qc.sh` script, which allows an arbitrary output directory to be specified.
If the option is not specified then the output directory defaults to a `qc` subdirectory of the current working directory (i.e. same as the behaviour before the update).
> Enable setting of custom qc output directory for illumina qc.sh

- QC-pipeline/fastq_screen.sh
- QC-pipeline/illumina_qc.sh
PR to reduce the default subset size used in `fastq_screen.sh` and `illumina_qc.sh`, to bring it into line with the default subset the `fastq_screen` program itself uses (from 1000000 to 100000).
> Reduce the default subset size used for fastq_screen in QC pipeline

- NGS-general/extract_reads.py
- bcftbx/ngsutils.py
- bcftbx/test/test_ngsutils.py
- bcftbx/test/test_utils.py
- bcftbx/utils.py
- docs/source/bcftbx.rst
- docs/source/bcftbx/ngsutils.rst
- docs/source/bcftbx/utils.rst
PR to move the generic file reading functions from the `extract_reads.py` utility into the `bcftbx` Python library, to enable reuse elsewhere:
* `getlines`: generic buffered line-by-line file reader
* `get_read_size`: return number of lines per record depending in sequence file based on file extension
* `getreads`, `getreads_subset`, `getreads_regexp`: extract reads from a sequence file
> Move generic file reading functions from 'extract_reads.py' into bcftbx library

- bcftbx/test/test_utils.py
- bcftbx/utils.py
PR to enable the `mkdir` function to create any missing intermediate directories, if new `recursive` option is set to `True`. Default remains to operate non-recursively.
> bcftbx/utils: enable 'mkdir' function to make missing intermediate directories

- bcftbx/IlluminaData.py
- bcftbx/test/test_IlluminaData.py
The `SampleSheetPredictor.set` method was implicitly replacing previously set values with defaults for all parameters not explicitly specified when the method was called.
This PR fixes the `set` method so that previously set values are preserved unless explicitly changed in the `set` call.
> Fix 'set' method for SampleSheetPredictor in bcftbx/IlluminaData.py

- bcftbx/cmdparse.py
- bcftbx/test/test_cmdparse.py
As mentioned in issue #46, refactored bcftbx/cmdparse module to use argparse
> refactored cmdparse.py to use argparse instead of optparse

- bcftbx/cmdparse.py
This PR makes some largely cosmetic updates to the `bcftbx/cmdparse.py` module, including:
* Updating docstrings to more accurately document usage following generalisation to allow `argparse` to be used for parser backend (PR #54)
* Re-establishing consistent coding style
(There is also some minor refactoring to abstract repeated code in the `add_*_command` functions.)
This PR contributes to addressing issue #46.
> Docstring and code tidying for cmdparse module

- bcftbx/IlluminaData.py
- bcftbx/test/test_IlluminaData.py
This PR aims to address a special case of IEM sample sheets, when the `[Header]` section contains values which are double-quoted and which also contain commas.
The PR should help to fix the bug in this issue (which also contains more details): https://github.com/fls-bioinformatics-core/auto_process_ngs/issues/144
> Fix handling of quoted values with commas in IEM sample sheets

- bcftbx/cmdparse.py
- bcftbx/test/test_cmdparse.py
PR to fix bug with the "standard" option functions in `bcftbx.cmdparse` (e.g. `add_nprocessors`) when an instance of `optparse.OptionGroup` is supplied (see also comments in issue #46).
Updating `add_arg` to check for `OptionContainer` instances covers both `OptionParser` and `OptionGroup` (which are both subclassed off `OptionContainer`).
> bcftbx/cmdparse: test 'add_arg' function and fix for optparseOptionGroup instances

- bcftbx/JobRunner.py
Sometimes errors are seen in the unit testing of the https://github.com/fls-bioinformatics-core/auto_process_ngs repo which come from the `list` method of the `bcftbx.JobRunner.SimpleJobRunner` class: a `KeyError` exception is raised from the line:
del(self.__job_popen[job_id])
presumably because the job has finished and the dictionary entry has been removed by some background process (as this is an intermittent error it's difficult to check).
This PR adds a `try/except` block to handle this specific error and emit a warning.
> Fix SimpleJobRunner.list() to handle missing job ids

- NGS-general/reorder_fasta.py
- docs/source/reference/ngs_general.rst
PR to implement a utility `reorder_fasta.py` which can be used to put the chromosomes in a FASTA file into karyotypic order.
Some background: GATK3 can have problems with inputs where chromosomes are sorted lexographically rather than karyotypically: [Errors about contigs in BAM or VCF files not being properly ordered or sorted](https://software.broadinstitute.org/gatk/documentation/article?id=1328)
"Lexographic" sorting is essentially the ordering you get by sorting by ASCII characters, and gives ordering like:
chr10
chr11
chr1
chr2
...
"Karyotypic" sorting treats the digits as numbers and gives ordering like:
chr1
chr2
...
chr10
chr11
See also Biostars: [Question: Karyotypically Ordered Hg19](https://www.biostars.org/p/9888/)
> WIP utility to reorder chromosomes karyotypically in FASTA

- bcftbx/IlluminaData.py
- bcftbx/test/test_IlluminaData.py
Implement a new function `split_run_name_full`, which also extracts the flow cell ID and prefix from the run name, and refactor `split_run_name` to call this new function to get a subset of items from the run name.
> bcftbx/IlluminaData: add function to extract all elements from run names (incl flow cell ID)

- bcftbx/IlluminaData.py
- bcftbx/test/test_IlluminaData.py
Address issue #61 by adding an optional `platform` argument to the `IlluminaRun` class in `bcftbx.IlluminaData` module, which overrides the built-in platform-detection (and allows platform to be specified for sequencers with instrument names which aren't listed in `platforms.py`).
> bcftbx/IlluminaData: allow platform to be set explicitly for IlluminaRun

- bcftbx/IlluminaData.py
- bcftbx/test/test_IlluminaData.py
PR to address an issue with the `fix_base_mask` function in `bcftbx/IlluminaData`, when a zero length barcode is supplied (was masking the index reads incorrectly e.g. generating `I0nnnnnn` rather than `nnnnnn`).
> bcftbx/IlluminaData: update 'fix_bases_mask' for empty barcode sequences

- bcftbx/JobRunner.py
PR to fix a bug in the `GEJobRunner` class (in `bcftbx/JobRunner.py` ), when arguments containing whitespace are supplied to the `run` method.
Without this fix the generated command which is sent via `qsub` is incorrectly parsed and will either fail, or not be executed as originally intended.
> GEJobRunner: quote script arguments containing whitespace

- .travis.yml
- ChIP-seq/make_macs2_xls.py
PR to add a new `--bed` option which outputs a BED-like file with columns `chr`, `abs_summit-100` and `abs_summit+100` in addition to the XLSX file produced by default.
> [WIP] Update 'make_macs2_xls.py' to enable additional output BED file

- QC-pipeline/fastq_strand.py
PR to update `fastq_strand.py` so that it can be run on either single-end (i.e. single Fastq input) or paired-end data (pair of Fastqs).
> [WIP] enable fastq_strand.py to be run on single end data

- QC-pipeline/illumina_qc.sh
PR to add a new option `--no-screens` to the `illumina_qc.sh` script, to suppress running of `fastq_screen`.
> illumina_qc.sh: add option to disable Fastq_screen

- bcftbx/JobRunner.py
- bcftbx/mockGE.py
- bcftbx/test/test_JobRunner.py
Extends PR #73 to try and remove all calls to `qstat` from `GEJobRunner` for monitoring jobs.
> [WIP] remove 'qstat' calls from GEJobRunner for job monitoring

- bcftbx/JobRunner.py
- bcftbx/mockGE.py
- bcftbx/test/test_JobRunner.py
PR to implement optimisations for the `JobRunner/GEJobRunner` class, with the aim of reducing the number and frequency of calls to Grid Engine utilities `qstat` and `qacct` (and in turn reduce the overhead imposed on GE).
Significant changes:
* **Implement "mock" versions of GE utilities for testing/development**: includes a new `mockGE` module that provides a mock implementation of the GE functions for test and development purposes, and updates the unit tests to make use of it (so tests now run even if Grid Engine is not available in the testing environment).
* **Remove all calls to `qacct`**: reimplements how jobs are run and how exit codes are collected, to remove the need to call `qacct`. Now creates wrapper scripts for each job which capture the exit status from the supplied command, …
> [WIP] Optimisations for the GEJobRunner class

- QC-pipeline/fastq_strand.py
PR to address issue #70 for `fastq_strand.py`:
* Updates unit tests to check different failure modes
* Remove pre-existing output file
* Write final output file only on successful completion
* Clean up working directory regardless of success or failure
> fastq_strand.py: improvement to handling outputs on failure

- bcftbx/test/test_utils.py
- bcftbx/utils.py
PR to reimplement the `bcftbx.utils` `AttributeDictionary` class as a subclass of `dict`, and add a test to ensure that it can be pickled and unpickled.
> Reimplement the AttributeDictionary class so it can be pickled

- bcftbx/IlluminaData.py
- bcftbx/test/test_IlluminaData.py
The `split_run_name_full`  needs to be updated to handle run names which use a full four-digit year in the datestamp, e.g. for the iSeq platform:
20180829_FS10000171_3_BNT40323-1530
> Allow 4 digit years in run names when splitting into DATE, INSTRUMENT etc

- QC-pipeline/fastq_strand.py
PR updating the `fastq_strand.py` utility to handle the case when `STAR` completes successfully but no reads from the input Fastqs are mapped. In this case the total count of mapped reads is zero and this results in a `ZeroDivision` exception from `fastq_strand.py`.
With this update, the program will instead report the forward and reverse psuedo-percentages as both being zero and complete without an error.
> Fix fastq_strand.py to handle no mapped reads from STAR

- bcftbx/utils.py
PR removes logging debug statements from the `mkdir` and `mklink` functions in `bcftbx.utils`; these were generating excessive amounts of output in testing which weren't helping to understand failures.
> bcftbx/utils: remove debug statements from 'mkdir' and 'mklink'

- QC-pipeline/illumina_qc.sh
PR which fixes a bug in `QC-pipeline/illumina_qc.sh` when using the `--no-screens` option (which suppresses `fastq_screen` runs). In this case if new permissions were also specified in the `qc.setup` script then `illumina_qc.sh` would fail when trying to set permissions on the missing `fastq_screen` outputs.
> Fix failure in 'illumina_qc.sh' script using --no-screens option

- QC-pipeline/fastq_strand.py
PR which bumps version of `fastq_strand.py` to 0.0.4 to mark the changes implemented to handle strandedness edge cases etc in PR #81.
> QC-pipeline/fastq_strand.py: bump version to 0.0.4.

- bcftbx/JobRunner.py
PR which improves the locking of job finalization in the `GEJobRunner` class - the previous implementation (check a dictionary entry: if the key is not found then create it and assign it as `True`) still exhibits failures due to race conditions.
The reimplementation uses the following procedure:
* Create a new lock entry in a dictionary where the key is a combination of the job id, timestamp and unique ID
* Check for any other lock entries where the first part of the key is the same as the job id; if one is found then compare the timestamps
* If the new timestamp is newer than the existing one then the existing lock takes precedence; the new lock is abandoned
* If the new timestamp is older than the existing one then the "new" lock takes precedence
* If the timestamps are identical then …
> GEJobRunner: improve lock on job finalization

- bcftbx/IlluminaData.py
- bcftbx/test/test_IlluminaData.py
PR to address issue #86: updates the `SampleSheet` class in `bcftbx/IlluminaData` so that it can handle the 'Manifests' section of IEM sample sheet files.
The sample sheet specification is described here:
https://emea.illumina.com/content/dam/illumina-marketing/documents/products/technotes/sequencing-sheet-format-specifications-technical-note-970-2017-004.pdf
The 'Manifests' section looks like e.g.
[Manifests]
A,TruSeqAmpliconManifest-1.txt
B,TruSeqAmpliconManifest-2.txt
and consists of key,filename pairs.
According to the documentation:
> The Data section should also contain a Manifest column to assign a Manifest to each sample. Each sample can be assigned exactly one Manifest, but different samples may be assigned different Manifests
e.g.
[Data] …
> bcftbx/IlluminaData: update SampleSheet to handle 'Manifests' section in IEM sample sheet files

- bcftbx/JobRunner.py
Grid Engine doesn't allow job names to start with a digit, so this PR updates the job name sanitisation in the `GEJobRunner` class to add an underscore if this is the case.
The PR also updates the list of characters that are sanitised to include `@`, `/` and `?`.
> Update GEJobRunner name sanitisation to handle job names starting with digits

- bcftbx/JobRunner.py
PR to fix bug introduced in the `GEJobRunner` class (in `bcftbx/JobRunner`) from previous PR #90, which breaks updating job grace periods in certain circumstances.
> Fix bug when updating grace period in GEJobRunner

- bcftbx/mock.py
PR which updates the `add_fastq_batch` and `add_undetermined` methods of the `MockIlluminaData` class to accept a new optional `reads` argument, which allows arbitrary sets of reads to be created
e.g. ('R1','R2','I1'). This should help with testing of functionality which works with the output of software which creates index reads etc.
> bcftbx/mock: update MockIlluminaData class to create arbitrary read sets

- QC-pipeline/run_qc_pipeline.py
- bcftbx/JobRunner.py
PR which addresses issue #74 by removing the `DRMAAJobRunner` class from the `bcftbx/JobRunner` module. It also removes support for this runner in the `run_qc_pipeline.py` utility.
> Remove 'DRMAAJobRunner' class from bcftbx/JobRunner module

- .travis.yml
- illumina2cluster/prep_sample_sheet.py
PR which fixes a bug in the `illumina2cluster/prep_sample_sheet.py` utility, introduced by the switch to `argparse` - the `-v` option is defined twice as shorthand for the implicit `--version` option as well as for the `--view` option. This change updates the shorthand for `--view` to be `-V`.
> Fix parser conflict for -v option in 'prep_sample_sheet.py' utility

- bcftbx/cmdparse.py
- bcftbx/test/test_cmdparse.py
PR which updates the `bcftbx/cmdparse` module so that it no longer depends explicitly on the deprecated `optparse` library. Instead the `argparse.ArgumentParser` is used as the default parser class from now on.
(This PR should address the outstanding parts of issues #46 and #68.)
> bcftbx/cmdparse: fixes and updates to move to argparse

- ChIP-seq/make_macs2_xls.py
PR which fixes a `print` function call in `make_macs2_xls.py` where we don't want a trailing new line (requires the version of `print` from `__future__`).
> ChIP-seq/make_macs2_xls.py: fix print function call

- bcftbx/Spreadsheet.py
PR to fix the syntax for capturing an exception, for Python 3 compatibility.
> 'bcftbx/Spreadsheet': fix exception capturing syntax

- bcftbx/JobRunner.py
PR which addresses an intermittent bug in the `SimpleJobRunner` class, when trying to access info on a job which has been removed.
It's unclear what triggers the bug but I'm speculating that it's due to a race condition when the class is used in a threaded context (for example, within the `simple_scheduler` module from the `auto_process_ngs` package).
> bcftbx/JobRunner: SimpleJobRunner.list() should trap for 'missing' jobs

- QC-pipeline/fastq_strand.py
- bcftbx/JobRunner.py
- bcftbx/mockGE.py
- bcftbx/test/test_utils.py
PR to fix leading zeroes on octal numbers e.g. `0755`, which is valid for Python2 but not for Python3 (as numbers cannot have leading zeroes, they result in `SyntaxError: invalid token`).
The correct format is e.g. `0o755`, which is valid for both Python2 and 3.
> Fix leading zeroes on octal numbers for Python3 compatibility

- bcftbx/utils.py
PR which fixes a Python indentation error in the `bcftbx/utils` module (had a tab character rather than spaces).
> bcftbx/utils: fix Python indentation error

- bcftbx/IlluminaData.py
- bcftbx/cmdparse.py
- bcftbx/platforms.py
- bcftbx/simple_xls.py
PR which fixes the syntax for a number of relative imports in the `bcftbx` library which break when tested under Python 3.
> bcftbx: fix various relative imports which break under Python 3

- bcftbx/FASTQFile.py
PR which refactors the `FastqIterator` class in `bcftbx/FASTQFile` to be compatible with both Python 2 and 3, by renaming the existing `next` method to `__next__` (required for Python3) and reimplementing `next` (required for Python2) as wrapper for `__next__`.
Without this update attempts to instantiate `FastqIterator` under Python3 result in
TypeError: Can't instantiate abstract class FastqIterator with abstract methods __next__
> bcftbx/FASTQFile: update FastqIterator to be compatible with Python3

- bcftbx/FASTQFile.py
PR which updates `fastqs_are_pair` function in the `bcftbx/FASTQFile` module to be Python 2 and 3 compatible.
The update switches the import of `izip_longest` from `itertools` to be `zip_longest` imported from the `future.moves.itertools` module.
> bcftbx/FASTQFile: update 'fastqs_are_pair' function to be Python 2/3 compatible

- bcftbx/test/test_TabFile.py
PR which makes minor updates to a couple of the unit tests for the `bcftbx/TabFile` module so that they work with both Python 2 and 3.
The updates are:
* Import long int type (as this doesn't exist in Python3)
* Refactor test which compares float values (to avoid test failures due to rounding errors)
> bcftbx/TabFile: update the unit tests for compatibility with Python3

- bcftbx/TabFile.py
- bcftbx/test/test_TabFile.py
PR which updates the `bcftbxTabFile` classes (`TabFile` and `TabDataLine`) to give the option of observing Python PEP 515 (https://www.python.org/dev/peps/pep-0515/) and treat numbers with underscore characters as valid integers or floats (e.g. `1_000` or `4_283.7`).
By default PEP 515 is *not* observed (to preserve the current behaviour) so if these values are encountered then they will not be treated as numerical values. The PR enforces this for both Python 2 and 3.
By setting the `allow_underscores_in_numerical_literals` argument, PEP 515 compatibility is turned on for both Python 2 and 3 (so the behaviour is consistent between Python versions), and these values are converted to the appropriate numerical type.
> Update bcftbx/TabFile classes to handle underscores in numeric literals (PEP 515)

- bcftbx/mock.py
PR which makes updates to the `bcftbx/mock` module to ensure compatibility with Python 2 and 3.
Specifically:
* The Python 2-only `xrange` function is swapped for `range` from `functools` (available for both Python 2 and 3), and
* The type of data written to mock files is explicitly specified.
> bcftbx/mock: updates for Python 3 compatibility

- bcftbx/test/test_utils.py
- bcftbx/utils.py
PR which updates the `bcftbx/utils` module to fix compatibility issues between Python 2 and 3, including:
* Fixing relative imports in unit tests
* Removing `xrange` in favour of forwards-compatible `range` function
* Reimplementing use of `max` built-in function to handle `None` values
* Updating `getlines` to explicitly read data as text
* Fixing unit tests for `concatenate_fastq_files` when handling gzipped Fastqs
> bcftbx/utils: fixes for Python 2/3 compatibility

- bcftbx/Spreadsheet.py
PR which updates the `bcftbx/Spreadsheet` module to use either 'uppercase' (Python2) or 'ascii_uppercase' (Python3) as appropriate, and explicitly specify integer division operator in the `Worksheet.column_id_from_index()` method.
> bcftbx/Spreadsheet: fix 'Worksheet.column_id_from_index' for Python 2/3 compatibility

- bcftbx/SolidData.py
PR which updates the `bcftbx/SolidData` module to fix issues with Python 2/3 compatibility:
* Fix relative import of the `utils` module
* Switch to using `sorted(...,key=...)` function, instead of built-in list sorting method with `cmp`
* Implement `__bool__` methods for classes where `__nonzero__` was already implemented
> bcftbx/SolidData: fixes for Python2/3 compatibility issues

- bcftbx/simple_xls.py
- bcftbx/test/test_simple_xls.py
PR which implements a number of updates to the `bcftbx/simple_xls` module for Python 2/3 compatibility:
* Switch column sorting to use `sorted(...,key=...`)
* Reimplement the column indices comparison function to drop the `cmp` builtin (which is unavailable in Python3)
* Switch from `xrange` to Python3-compatible version of `range`
* Implement the `__bool__` method on the `XLSStyle` class in parallel with the existing `__nonzero__` method
* Implement the `__next__` method on the `ColumnRange` iterator class in parallel with the existing `next` method
* Fix the integer division operator (i.e. use `//` rather than `/`)
> bcftbx/simple_xls: fixes for Python2/3 compatibility

- bcftbx/cmdparse.py
- bcftbx/test/test_cmdparse.py
PR which fixes a problem in the `bcftbx/cmdparse` module when setting the version on subparsers for some versions of Python (specifically, in some versions the `argparse.ArgumentParser` class doesn't support a `version` parameter on instantiation).
The fix works around this by attempting to explicitly add the `--version` argument if it appears it is not implicitly supported at instantiation.
> bcftbx/cmdparse: handle --version on arbitrary subparsers

- bcftbx/test/test_ngsutils.py
PR which updates the `bcftbx/ngsutils` unit tests to be compatible with both Python 2 and 3, by replacing the `xrange` function with a Python 2 compatible-version of the `range` function.
> bcftbx/ngsutils: update unit tests to be compatible with Python 2 and 3

- bcftbx/test/test_IlluminaData.py
PR which updates the unit tests for the `IlluminaRun` class from `bcftbx/IlluminaData` module so that they operate in a temporary directory, rather than in the current working directory.
> bcftbx/IlluminaData: update unit tests for 'IlluminaRun' to operate in temp dir

- bcftbx/qc/report.py
PR which updates the in-place sorting of lists in the `bcftbx/qc/report` module to use `sorted(...,key=...)`, and drops comparison functions which are made redundant by these changes.
> bcftbx/qc/report: update sorting

- illumina2cluster/prep_sample_sheet.py
- illumina2cluster/report_barcodes.py
PR which updates utilities in the `illumina2cluster` directory for Python 2/3 compatibility:
* `prep_sample_sheet.py`: fixes `--version` option which was broken for Python 3, and
* `report_barcodes.py`: update sorting of dictionary keys, which was also broken for Python 3.
> Illumina2cluster: update utilities for Python3 compatibility

- QC-pipeline/fastq_strand.py
PR which fixes the `--version` option of the `QC-pipeline` `fastq_strand.py` utility, which was broken for Python3.
> fastq_strand.py: fix --version command line option for Python 3

- utils/md5checker.py
PR which fixes the `--version` option of the `utils` `md5checker.py` utility, which was broken under Python 3.
> md5checker.py: fix --version command line option for Python3

- NGS-general/manage_seqs.py
- NGS-general/reorder_fasta.py
- NGS-general/sam2soap.py
- NGS-general/split_fasta.py
- NGS-general/split_fastq.py
PR which updates the utilities in `NGS-general` for Python 2/3 compatibility:
* `manage_seqs.py`: fix `--version` command line option which was broken under Python 3, and explicitly cast dictionary keys to a list for Python 3
* `reorder_fasta.py`: switch from `izip_longest` in unit tests to a Python 2/3 compatible version of `zip_longest`
* `sam2soap.py`: switch from Python2-only `xrange` to Python2/3 compatible version of `range`
* `split_fasta.py`:  fix `--version` command line option which was broken under Python 3, and add `__next__` method to `FastaChromIterator` for Python 3
* `split_fastq.py`: fix the mode used to write gzipped test files in the unit tests
> NGS-general: update utilities for Python2/3 compatibility

- QC-pipeline/fastq_strand.py
PR which updates the `fastq_strand.py` utility to use a Python2- and 3-compatible `range` function instead of the Python2 only `xrange` function.
> fastq_strand.py: update 'xrange' to Python 3 compatible 'range' function

- bcftbx/JobRunner.py
- bcftbx/mockGE.py
PR which fixes the escaping of special characters in strings in the Python source code, for Python 3 compatibility.
> bcftbx: fix escaping special characters in Python source code

- bcftbx/IlluminaData.py
- bcftbx/test/test_IlluminaData.py
PR which fixes the `SampleSheet` class in `bcftbx/IlluminaData` for samplesheets where the 'key,value' lines which don't explicitly contain a delimiter or value (i.e. only consist of 'key').
For example, the `Description` field in the fragment below:
[Header]
IEMFileVersion,4
Date,11/16/2015
Workflow,GenerateFASTQ
Application,RNA-Seq
Assay,TruSeq LT
Description
Chemistry,Default
NB this implements an alternative fix to that in PR #147; it also adds a unit test case.
> bcftbx/IlluminaData: fix 'SampleSheet' class to handle 'key,value' lines with no delimiter or value

- bcftbx/IlluminaData.py
- bcftbx/test/test_IlluminaData.py
PR which fixes a bug in `split_run_name_full` (in the `bcftbx.IlluminaData` module) - the check on putative datestamps should include a call to the `digits` method but in fact just checked whether the method existed. As a result it was possible for invalid 6- and 8-character strings to pass as datestamps.
The fix now means that strings which are not composed of digits will always fail the test for whether they are valid datestamps.
> bcftbx/IlluminaData: fix error in call to 'digits' method in 'split_run_name_full'

- bcftbx/FASTQFile.py
- bcftbx/test/test_FASTQFile.py
PR which fixes various previously undiagnosed issues associated with `FastqIterator` and the `nreads` function in the `bcftbx/FASTQFile` module under Python3, when reading FASTQ data from files on disk (both uncompressed and gzipped).
> bcftbx/FASTQFile: fixes for Python2/3 compatibility when reading files from disk

- bcftbx/IlluminaData.py
PR which updates the `SampleSheetPredictor` class in `bcftbx/IlluminaData` to handle blank lane numbers in the input samplesheet.
> bcftbx/IlluminaData: 'SampleSheetPredictor' needs to handle blank lanes

- bcftbx/htmlpagewriter.py
- bcftbx/test/test_htmlpagewriter.py
PR which adds unit tests for the `PNGBase64Encoder` class in `bcftbx/htmlpagewriter` and updates the output to ensure that unicode strings are returned (for compatibility with Python 3).
> htmlpagewriter: update 'PNGBase64Encoder' for Python 3 compatibility

- config/qc.setup.sample
PR which updates the `qc.setup.sample` configuration for the QC scripts so that environment variables will override the default settings in the file, for example
$ export SET_GROUP=ls-bcf
should replace the default value in the configuration with the new value.
> Update 'qc.setup.sample' so user environment variables can override defaults

- .travis.yml
- LICENSE
- docs/source/config.rst
- setup.py
PR which extends the specific versions of Python which are supported/tested to include 3.6 and 3.8.
Also updates `setup.py` to include the supported versions and adds an explicit license (AFL-3).
> Extend supported Python 3 versions

- bcftbx/htmlpagewriter.py
PR which removes imports of the unused `platforms` and `TabFile` modules from the `htmlpagewriter` module of `bcftbx`.
> bcftbx/htmlpagewriter: remove unused imports

- bcftbx/IlluminaData.py
- bcftbx/test/test_IlluminaData.py
PR that updates the `SampleSheetPredictor` class in `bcftbx/IlluminaData` to enable automatic predictions including index reads (i.e. `I1`, and `I2` for paired-end data), or custom read specifications (e.g. `R1`, `R2`, `R3`).
> bcftbx/IlluminaData: update SampleSheetPredictor to deal with index/custom reads

- bcftbx/mock.py
PR updating the `MockIlluminaData.create()` method in `bcftbx/mock` to add an option that forces the creation of sample subdirectories in projects when mocking output from `bcl2fastq`.
> bcftbx/mock: add option to force creation of sample subdirectories in MockIlluminaData

- bcftbx/JobRunner.py
- bcftbx/mockGE.py
- bcftbx/test/test_JobRunner.py
PR which enables the number of available threads or cores to be set and accessed from job runners.
For `SimpleJobRunner` instances, the `nslots` option can be set to specify the number of available cores; for `GEJobRunner` instances the number of available cores is determined at run time from the `NSLOTS` environment variable. Both runners set a `BCFTBX_RUNNER_NSLOTS` environment variable so that processes run by the runners can access and use this number if required.
> JobRunner: enable slots/cores/threads to be set within runners

- bcftbx/FASTQFile.py
- bcftbx/JobRunner.py
- bcftbx/Md5sum.py
- bcftbx/htmlpagewriter.py
- bcftbx/mockGE.py
- bcftbx/test/test_JobRunner.py
- bcftbx/test/test_Md5sum.py
- bcftbx/test/test_TabFile.py
- bcftbx/test/test_utils.py
- bcftbx/utils.py
PR which fixes `ResourceWarning` warnings from the unit tests when run under Python 3. The warnings are related to things like unclosed files and processes that are still running when the Python process ends, both in test cases and in the `bcftbx` code.
> bcftbx: fix 'ResourceWarnings' for unit tests run under Python 3

- bcftbx/JobRunner.py
Bugfix PR which corrects a typo in the `SimpleJobRunner` class (in the `bcftbx/JobRunner` module), where `os.getcwd()` was incorrectly called as `os.get_cwd()`.
> bcftbx/JobRunner: fix typo in 'os.getcwd()' call in 'SimpleJobRunner'

- bcftbx/JobRunner.py
- bcftbx/test/test_JobRunner.py
PR which updates the `SimpleJobRunner.__repr__` built-in function (in `bcftbx/JobRunners`) so that it includes the `nslots` and `join_logs` settings, for example:
str(SimpleJobRunner(nslots=8,join_logs=True)
should return
'SimpleJobRunner(nslots=8 join_logs=True)'
The PR also updates the `fetch_runner` function to handle the `join_logs` setting for `SimpleJobRunners` if it is supplied as part of the runner definition; this should mean that feeding the result of `__repr__` into `fetch_runner` will return a runner with the same configuration.
> SimpleJobRunner: update '__repr__' and 'fetch runner' for joining logs

- bcftbx/IlluminaData.py
- bcftbx/test/test_IlluminaData.py
PR that updates the `SampleSheet` class in `bcftbx/IlluminaData.py` to remove data from trailing empty lines after the `[Data]` section in an input sample sheet file.
Previously any empty lines would result in blank lines being stored in the `data` section of a `SampleSheet` instance, which could cause problems for sorting etc.
> bcftbx/IlluminaData: remove trailing empty lines in 'SampleSheet' class

- bcftbx/IlluminaData.py
- bcftbx/test/test_IlluminaData.py
PR which extends the data items from the `RunInfo.xml` file which are exposed by the `IlluminaRunInfo` class (issue #164).
New attributes are:
* `instrument` (instrument ID, taken from the `<Instrument>` tag)
* `date` (run datestamp, taken from the `<Date>` tag)
* `flowcell` (flowcell ID, taken from the `<Flowcell>` tag)
* `lane_count` (flowcell lane count, taken from the `<FlowcellLayout LaneCount=... >` attribute)
> bcftbx/IlluminaData: extend data items exposed by 'IlluminaRunInfo' class

- bcftbx/IlluminaData.py
- bcftbx/test/test_IlluminaData.py
PR which extends the `IlluminaRun` class in `bcftbx/IlluminaData` to add two new attributes:
* `sample_sheet` (`SampleSheet` instance populated with the sample sheet file contents, if present)
* `runinfo` (`IlluminaRunInfo` instance populated with the `RunInfo.xml` contents, if present)
Aims to address issue #165.
> IlluminaRun: expose sample sheet and RunInfo.xml data via 'SampleSheet' and 'IlluminaRunInfo' instances

- bcftbx/IlluminaData.py
- bcftbx/platforms.py
- bcftbx/test/test_IlluminaData.py
PR which modifies the platform detection mechanism in the `IlluminaRun` class (in `bcftbx/IlluminaData`), to prevent failures when the run directory looks like Illumina sequencer output but a platform cannot be assigned by matching the instrument name to one of the sequencers in `bcftbx/platforms`. In this case the platform is assigned to be generic `illumina`.
Now an exception is only raised when the run directory doesn't look like output from an Illumina sequencer (and the instrument name doesn't match a known platform, and the platform is not explicitly supplied on `IlluminaRun` instantiation).
This PR partially addresses issue #159; while it doesn't drop the platform detection mechanism completely, it should prevent it being an issue in future when handling data from new sequencers.
> Modify platform detection in 'llluminaRun' class

- bcftbx/TabFile.py
- bcftbx/test/test_TabFile.py
PR which updates `TabFile.appendColumn()` to accept an optional 'fill value' to use when populating new column in each row.
> bcftbx/TabFile: allow an optional 'fill' value to be specified when appending a new column

- bcftbx/mock.py
PR which fixes an issue in the `RunInfoXml` class in `bcftbx/mock`, which is used to generate mock versions of the `RunInfo.xml` file from Illumina sequencer run directories.
Previously the flowcell ID extracted from the run name was not being set correctly in the XML file; this update fixes the issue.
> bcftbx/mock: update mock 'RunInfoXml' to set the flowcell ID correctly

- bcftbx/TabFile.py
- bcftbx/test/test_TabFile.py
PR which extends the `TabFile` class in `bcftbx/TabFile` so that it will keep commented lines (i.e. lines starting with a `#` symbol); by default these lines are ignored on loading the data. When commented lines are preserved then leading `#` symbols become part of the data item in the first column of the file.
> bcftbx/TabFile: add functionality to 'TabFile' to handle commented lines

- illumina2cluster/verify_paired.py
PR which fixes the broken `--version` option of the `verify_paired.py` utility, which affects Python 3.6.
> verify_paired.py: fix broken '--version' CLI option

- illumina2cluster/prep_sample_sheet.py
PR which updates the `prep_sample_sheet.py` utility in `illumina2cluster` to add a new `--reverse-complement-i5` option, which will reverse complement the i5 indices in a sample sheet file.
> prep_sample_sheet.py: add option to reverse complement i5 index

- docs/source/conf.py
PR which updates the documentation generation via Sphinx, to use the `napoleon` extension to handle "Google-style" class and function docstrings:
https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html
> Update Sphinx documentation generation to use the 'napoleon' extension

- bcftbx/TabFile.py
- bcftbx/cli/best_exons.py
- bcftbx/test/test_TabFile.py
PR which relocates the `TabFileIterator` class from the `best_exons.py` utility into the `bcftbx.TabFile` module, addressing issue #142.
> Relocate 'TabFileIterator' from 'best_exons.py' into TabFile module

- setup.py
PR which tidies up after PR #198, by removing the code that attempts to collect scripts and utilities for installation from the now-defunct `utils` subdirectory.
> setup.py: remove attempt to install scripts from defunct 'utils' dir

- bcftbx/cli/fastq_strand.py
PR which updates the `fastq_strand.py` utility to use a module-specific logger (rather than the default "root" logger offered by the `logging` module) when issuing warnings and critical error messages. This should make it clearer which component of the system has issued the messages.
> Update logging in 'fastq_strand.py'

- bcftbx/IlluminaData.py
- bcftbx/platforms.py
PR which updates the `bcftbx` library code to add `novaseq6000` (for Illumina's NovaSeq 6000 instrument) as a recognised sequencer platform.
> Add NovaSeq 6000 as recognised sequencing platform

- CHANGELOG.rst
- bcftbx/__init__.py
New version 1.12.0 to update stable version with all changes since previous release (1.11.1) - see `CHANGELOG` for summary.
> genomics-bcftbx version 1.12.0

- .github/workflows/python-ci.yml
Update the Github Python CI workflow to explicitly use ubuntu-20.04 (rather than ubuntu-latest), in order to fix errors with Python 3.6 tests (since Python 3.6 is EOL and not supported by ubuntu-22.04 - see https://github.com/actions/setup-python/issues/544#issuecomment-1332535877).
> Update Github Python CI workflow to fix missing Python 3.6

- bcftbx/IlluminaData.py
- bcftbx/test/test_IlluminaData.py
Fixes a bug in the `IlluminaData` class (in `bcftbx/IlluminaData.py`) for `bcl2fastq2`-style outputs, when "mixed" Fastq names are found where some have lane numbers and others don't.
This situation can occur if the `bcl2fastq`-style output directory has actually been assembled from multiple runs of Fastq generation software where some projects have had e.g. `--no-lane-splitting` specified and others haven't.
In these cases the bug manifested itself as an error trying to sort the collected lane numbers (which had been acquired from the Fastq file names) (as the non-lane-split Fastqs return the lane as `None`). The fix is to remove the `None` lane designation from the list whenever such a mixture is encountered.
> bcftbx/IlluminaData: fix bug in IlluminaData class for mixed lane/no lane Fastqs

- bcftbx/IlluminaData.py
- bcftbx/test/test_IlluminaData.py
Fix a bug in the `IlluminaProject` class of `bcftbx/IlluminaData`, where Fastqs are "double assigned" for `undetermined` when a mixture of Fastq names with and without lanes is encountered.
The bug manifested as the Fastqs without lanes being assigned twice, to their own "sample" and also appended to the "laned samples". The update ensures that each undetermined Fastq is only assigned to a single "sample".
> bcftbx/IlluminaData: fix bug in IlluminaProject assigning undetermined Fastqs

- bcftbx/Md5sum.py
Reimplements the `md5sum` function to reduce the memory footprint when operating on large files, based on the Stack Overflow answer at https://stackoverflow.com/a/1131255/579925 (responding to the question "[Get the MD5 hash of big files in Python](https://stackoverflow.com/questions/1131220/get-the-md5-hash-of-big-files-in-python)"). The original implementation would run out of memory for large files.
> bcftbx/Md5sum: reimplement 'md5sum' function to reduce memory footprint

- bcftbx/mock.py
Updates the `MockIlluminaRun` class in `bcftbx/mock` module:
* Allows the flowcell mode to be set explicitly on creation of a `MockIlluminaRun` instance
* Adds `miniseq` as a known platform
* Creates additional run completion files in output mock run directory (determined by platform)
* Creates (empty) `InterOp` subdirectory in output mock run directory
> bcftbx/mock: updates to 'MockIlluminaRun' class

- bcftbx/test/test_utils.py
- bcftbx/utils.py
Add a new function `convert_size_to_bytes` in the `bcftbx/utils` module, to convert human-readable string representations of file sizes (e.g. `20M`, `1.5T` etc) to the equivalent size in bytes (essentially the reverse of the existing `format_file_size` function).
> bcftbx/utils: new function 'convert_size_to_bytes'

- CHANGELOG.rst
- bcftbx/__init__.py
New version 1.13.0 to update stable version with all changes since previous release (1.12.0) - see CHANGELOG for summary.
> genomics-bcftbx version 1.13.0

- bcftbx/mock.py
Fixes a bug in the `MockIlluminaRun` class when the platform is set to `novaseq`, which resulted in the `I1` index having zero cycles assigned in the mock `RunInfo.xml` file. The error was due to a problem in the default bases mask, where was supplied rather than `I10` for the first index read.
The PR also adds an assertion when generating the mock `RunInfo.xml` file, to check that the number of cycles is greater than zero.
> bcftbx/mock: fix bug in 'MockIlluminaRun' when generating mock NovaSeq runs

- CHANGELOG.rst
- bcftbx/__init__.py
Patch release 1.13.1 to update stable version with bug fixes in previous release (1.13.0) - see CHANGELOG for summary.
> genomics-bcftbx version 1.13.1

- bcftbx/IlluminaData.py
- bcftbx/mock.py
- bcftbx/platforms.py
- bcftbx/test/test_IlluminaData.py
Add information to the `platforms` module listing known sets of run completion files for Illumina sequencers. These are sets of files which indicate by their presence (or absence) whether a sequencing run has finished (or not).
A new function `get_run_completion_files` enables the lists to be retrieved for arbitrary platforms, and is also used in the `MockIlluminaRun` class (in the `mock` module) when creating mock sequencing runs for different sequencers.
> Update 'platforms' module to include info on run completion files

- .readthedocs.yaml
- docs/requirements.txt
- docs/source/conf.py
- requirements.txt
Updates to the documentation configuration for ReadTheDocs (RTD):
* Updates the configuration to fix documentation build failures on RTD
* Explicitly installs and uses the RTD theme
> Documentation fixes and updates for ReadTheDocs

- bcftbx/platforms/__init__.py
- setup.py
Refactors the `platforms` module into a subpackage within `bcftbx`, i.e.
platforms.py -> platforms/__init__.py
This shouldn't affect how the module and its members are imported, but it will make it easier to start refactoring the library to create further modules or packages within the `platforms` subpackage for specific sequencing platforms (as part of an anticipated reorganisation of the library).
> bcftbx: refactor 'platforms' module into subpackage

- bcftbx/JobRunner.py
- bcftbx/test/test_JobRunner.py
Add test for `GEJobRunner` class in `bcftbx/JobRunner` module to ensure that it can handle `-pe amd.pe` as well as `-pe smp.pe` when collecting the number of cores (aka `NSLOTS`).
The functionality was already present but this test makes it explicit (along with an update to the docstring for the `nslots` method of `GEJobRunner`).
> Ensure GEJobRunner can handle '-pe amd.pe' when collecting NSLOTS

- bcftbx/simple_xls.py
The `bcftbx.simple_xls` module is broken when trying to write XLSX format output using version 3.2.2 of the external Xlsxwriter library module (https://pypi.org/project/XlsxWriter/).
The bug is due to the `simple_xls` module using the `set_color` method of the `Format` class, which appears to have been removed in Xlsxwriter 3.2.2. The fix is to replace the call to `set_color` with `set_font_color`.
> Fix bug in 'simple_xls' module when using Xlsxwriter 3.2.2

- .github/workflows/python-ci.yml
- docs/source/requirements.rst
Updates the workflow for the CI testing via GitHub Actions, to replace the ubuntu-20.04 hosted runner (which closes down in April 2025) with the ubuntu-24.04 runner.
> Replace defunct 'ubuntu-20.04' runner for CI tests & update Python versions

- bcftbx/JobRunner.py
- bcftbx/mockslurm.py
- bcftbx/test/test_JobRunner.py
Implements a new job runner `SlurmRunner` in `bcftbx/JobRunner.py` which should enable the use of Slurm as a job submission engine.
Useful resources:
* https://slurm.schedmd.com/sbatch.html (Slurm `sbatch` documentation)
* https://docs.hpc.shef.ac.uk/en/latest/hpc/scheduler/#gsc.tab=0 (Slurm on Sheffield Uni HPC)
* https://ri.itservices.manchester.ac.uk/csf4/batch/sge-to-slurm/ (UoM CSF4 SGE-to-SLURM conversion)
This is a work-in-progress.
> WIP implement job runner for Slurm

- CHANGELOG.rst
- bcftbx/__init__.py
Release 1.14.0 to bring minor updates and fixes into stable version - see CHANGELOG for summary.
> genomics-bcftbx version 1.14.0
